name: deploy-backend-int222
on:
  push:
    branches:
      - main
jobs:
  loginVM:
    runs-on: ubuntu-20.04
    steps:
      - name: remote SSH command using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
  build:
    needs: loginVM
    runs-on: ubuntu-20.04
    steps:
      - name: build images docker-compose
        run: |
          cd int222-backend
          git pull origin main
          sudo docker-compose build
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        run: |
          docker run -d int222-backend
  logoutVM:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: log out vm
        run: |
          exit
